export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const SAVE_USER_INFO_SUCCESS = 'SAVE_USER_INFO_SUCCESS';
export const SAVE_USER_INFO_ERROR = 'SAVE_USER_INFO_ERROR';
export const CLEAN_STORE = 'CLEAN_STORE';

export const SAVE_SHIPMENT_STATE = 'SAVE_SHIPMENT_STATE';

export const ADD_MESSAGE = 'ADD_MESSAGE';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
